swagger: '2.0'
info:
  title: api_sprint1
  description: API
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /msg
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /perevaladded/:
    post:
      operationId: perevaladded_create
      description: ''
      parameters:
        - name: data
          in: fromData
          required: true
          schema:
            $ref: '#/definitions/PerevalAdded'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/PerevalAdded'
      tags:
        - perevaladded
    parameters: []
definitions:
  User:
    required:
      - email
      - fam
      - name
      - otc
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      email:
        title: Email
        type: string
        format: email
        maxLength: 254
        minLength: 1
      fam:
        title: Fam
        type: string
        maxLength: 150
        minLength: 1
      name:
        title: Name
        type: string
        maxLength: 150
        minLength: 1
      otc:
        title: Otc
        type: string
        maxLength: 150
        minLength: 1
      phone:
        title: Phone
        type: string
        pattern: ^\+?1?\d{9,12}$
        maxLength: 14
  Coord:
    required:
      - latitude
      - longitude
      - height
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      latitude:
        title: Latitude
        type: number
      longitude:
        title: Longitude
        type: number
      height:
        title: Height
        type: number
  Image:
    required:
      - title
      - data
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      title:
        title: Title
        type: string
        maxLength: 255
        minLength: 1
      data:
        consumes:
          - multipart/form-data
        parameters:
          - name: file
            in: formData   # <-----
            description: The uploaded file data
            required: true
            type: file
  PerevalAdded:
    required:
      - title
      - beauty_title
      - other_titles
      - user
      - coords
      - winter
      - summer
      - autumn
      - spring
      - images
    type: object
    properties:
      title:
        title: Title
        type: string
        maxLength: 255
        minLength: 1
      beauty_title:
        title: Beauty title
        type: string
        maxLength: 255
        minLength: 1
      other_titles:
        title: Other titles
        type: string
        maxLength: 255
        minLength: 1
      connect:
        title: Connect
        type: string
        maxLength: 1
        minLength: 1
      user:
        $ref: '#/definitions/User'
      coords:
        $ref: '#/definitions/Coord'
      winter:
        title: Winter
        type: string
        maxLength: 100
        minLength: 1
      summer:
        title: Summer
        type: string
        maxLength: 100
        minLength: 1
      autumn:
        title: Autumn
        type: string
        maxLength: 100
        minLength: 1
      spring:
        title: Spring
        type: string
        maxLength: 100
        minLength: 1
      images:
        schema:
          type: array
          items:
            type: object
            $ref: '#/definitions/Image'
